modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_display_url}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="creativecore"
type="required"
ordering="NONE"
side="BOTH"
versionRange="[${creativecore_version},)"

[[dependencies.${mod_id}]]
modId="littletiles"
type="required"
ordering="NONE"
side="BOTH"
versionRange="[${littletiles_version},)"

